import React, { useEffect, useState } from "react";
import styled from "styled-components";
import AlbumCard from "./AlbumCard";
import { Grid } from "@material-ui/core";

const SectionContent = styled.section`
	background-color: #292946;
	max-width: 600px;
	@media (min-width: 1000px) {
		max-width: 1270px;
	}
`;

const Section = styled(SectionContent)`
	margin: 0 auto;
	padding: 3em 2em;
`;

const Wrapper = styled(Section)`
	min-height: 100vh;
`;

const TitleText = styled.p`
	color: #fff;
	font-size: 40px;
	font-weight: 600;
`;

const StyledGrid = styled(Grid)`
	.MuiGrid-grid-xs-10 {
		flex-basis: 0;
	}
`;

const PhotoPage = () => {
	/**
	 * album info schema
	 * AlbumInfo: array {
	 * 	id: str (auto generated by firebase),
	 * 	title: string,
	 * 	coverImageSrc: string
	 * }
	 *
	 * example in useState
	 */
	const [albumInfo, setAlbumInfo] = useState(
		[...Array(9)].fill({
			id: "12345",
			title: "title is",
			coverImageSrc: "",
		})
	);

	useEffect(() => {
		// TODO: get album info from firebase
	}, [albumInfo]);

	return (
		<Wrapper>
			<TitleText>Albums</TitleText>
			<StyledGrid
				container
				alignItems="center"
				justifyContent="center"
				spacing={10}
			>
				{albumInfo.map((item, index) => {
					return (
						<StyledGrid
							key={index}
							item
							xs={10}
							sm={6}
							md={4}
							lg={3}
						>
							<AlbumCard
								id={`${index}${item.id}`}
								title={`${item.title} ${index + 1}`}
								coverImageSrc={item.coverImageSrc}
							/>
						</StyledGrid>
					);
				})}
			</StyledGrid>
		</Wrapper>
	);
};

export default PhotoPage;
